
// Objective-C API for talking to the following Go packages
//
//	github.com/vultisig/go-wrappers/go-dkls/sessions
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Godkls_FRAMEWORK_H__
#define __Godkls_FRAMEWORK_H__

#include "Session.objc.h"
#include "Universe.objc.h"

#endif
